const STATUS_CODES = {
  SERVER_ERROR: 500,
  OK: 200,
  CREATED: 201,
  NOT_FOUND: 404,
  UNAUTHORIZED: 401,
  BAD_REQUEST: 400,
  FORBIDDEN: 403,
};

const GENDER = {
  MALE: "M",
  FEMALE: "F",
};

module.exports = { STATUS_CODES, GENDER };
